on:
  push:
    branches: [main]
    paths:
      - main.tex
      - main.bib
      - .github/workflows/build.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan build
          git rm -rf .
          git add -f main.pdf
          git commit -m "Latest build"
          git push origin HEAD:build --force
          git checkout -f main
          git branch -D build
